### PR TITLE
Bugfix for state attribute warning 

### PR DESCRIPTION
**Pull request by ioBroker22**
This fixes Issue #350

### CODE REVIEW

**Comment by obakuhl** [comment]
I've tried to do this manually (change type from 'mixed' to 'number' in main.js), but without success. Did the warning disappear in your instance?

**Comment by obakuhl** [comment]
Alright, I did the same, I installed the commit and everything works now. Thx.

**Comment by ioBroker22** [comment]
No problem, i´m glad it works at your instance.

**Comment by DutchmanNL** [comment]
thank you

**Pull request merged**
